/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as EngineeringDrawingsRouteImport } from './routes/engineering-drawings'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FilesRouteImport } from './routes/files'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringDrawingsRoute = EngineeringDrawingsRouteImport.update({
  id: '/engineering-drawings',
  path: '/engineering-drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configure': typeof ConfigureRoute
  '/engineering-drawings': typeof EngineeringDrawingsRoute
  '/faq': typeof FaqRoute
  '/files': typeof FilesRoute
  '/invoice': typeof InvoiceRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configure': typeof ConfigureRoute
  '/engineering-drawings': typeof EngineeringDrawingsRoute
  '/faq': typeof FaqRoute
  '/files': typeof FilesRoute
  '/invoice': typeof InvoiceRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configure': typeof ConfigureRoute
  '/engineering-drawings': typeof EngineeringDrawingsRoute
  '/faq': typeof FaqRoute
  '/files': typeof FilesRoute
  '/invoice': typeof InvoiceRoute
  '/tools': typeof ToolsRouteWithChildren
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/configure'
    | '/engineering-drawings'
    | '/faq'
    | '/files'
    | '/invoice'
    | '/tools'
    | '/tools/$slug'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configure'
    | '/engineering-drawings'
    | '/faq'
    | '/files'
    | '/invoice'
    | '/tools/$slug'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/configure'
    | '/engineering-drawings'
    | '/faq'
    | '/files'
    | '/invoice'
    | '/tools'
    | '/tools/$slug'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfigureRoute: typeof ConfigureRoute
  EngineeringDrawingsRoute: typeof EngineeringDrawingsRoute
  FaqRoute: typeof FaqRoute
  FilesRoute: typeof FilesRoute
  InvoiceRoute: typeof InvoiceRoute
  ToolsRoute: typeof ToolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering-drawings': {
      id: '/engineering-drawings'
      path: '/engineering-drawings'
      fullPath: '/engineering-drawings'
      preLoaderRoute: typeof EngineeringDrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
  }
}

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfigureRoute: ConfigureRoute,
  EngineeringDrawingsRoute: EngineeringDrawingsRoute,
  FaqRoute: FaqRoute,
  FilesRoute: FilesRoute,
  InvoiceRoute: InvoiceRoute,
  ToolsRoute: ToolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
